# Generated by Django 3.2.19 on 2023-08-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230821_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Operator', 'Operator'), ('Customer', 'Customer')], max_length=30, null=True),
        ),
    ]
