# Generated by Django 3.2.19 on 2023-08-22 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_userlog_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
