# Generated by Django 3.2.19 on 2023-08-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_catalouge_catelougecertificate_catelougedatasheet_catelougefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceofinquiry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
