# Generated by Django 3.2.19 on 2023-08-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_inquirydetail_inquiryheader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inquirydetail',
            old_name='price',
            new_name='rate',
        ),
    ]
