# Generated by Django 3.2.19 on 2023-08-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_rename_price_inquirydetail_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirydetail',
            name='inquiryno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.inquiryheader'),
        ),
    ]
