# Generated by Django 3.2.19 on 2023-09-01 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master', '0010_auto_20230901_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimatioresourcedetail',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='estimatioresourcedetail',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='estimatioresourcedetail',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='estimatioresourceheader',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estresource', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimatioresourceheader',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
        migrations.AddField(
            model_name='estimatioresourceheader',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated Date'),
        ),
    ]
