# Generated by Django 3.2.19 on 2023-09-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_auto_20230901_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatioheader',
            name='net_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
