# Generated by Django 3.2.19 on 2023-09-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0013_estimatioheader_net_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatiodetail',
            name='estimation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='estimatioheader',
            name='net_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='estimatioresourcedetail',
            name='estimation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='estimatioresourceheader',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
