# Generated by Django 3.2.19 on 2023-11-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_auto_20230922_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatioheader',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
